config/routes.rb
# We don't namespace within the engine
# because engine would need to be mounted
# and routes would become /wherever-mounted/the-routes
# We want these routes to be in the main namespace
# AddressBook::Engine.routes.draw do

Rails.application.routes.draw do

  #constraints FeatureConstraint.new(:address_book) do
    resources :users, only: :none do
      resources :contact_lists
      resources :address_cards
    end
  #end
  resources :addresses, only: [:show, :edit, :update]
  resources :emails, only: [:show, :edit, :update]
  resources :phones, only: [:show, :edit, :update]
end

app/models/address.rb
class Address < ActiveRecord::Base
  validates :line_1, :city, :province, :postal_code, :country, presence: true
  belongs_to :addressable, polymorphic: true
  has_and_belongs_to_many :shipping_carrier_services

  def url_for_address
    "/addresses/#{id}"
  end

  def drop_down_display_value
    lines = [drop_down_line_1, drop_down_line_2]
    html_string = ""
    lines.each do |line|
      html_string << line
    end
    html_string.html_safe
  end

  def drop_down_line_1
    "#{addressable.first_name} #{addressable.last_name} &#13;"
  end
  def drop_down_line_2
    "#{line_1} #{line_2} #{city} #{province} #{postal_code}"
  end

  def formated_city_state_line
    "#{city}, #{province} #{postal_code}"
  end

end

app/models/address_card.rb
class AddressCard < ActiveRecord::Base
  has_many :emails
  has_many :addresses, as: :addressable
  has_many :phones
  has_and_belongs_to_many :contact_lists
  accepts_nested_attributes_for :emails, :allow_destroy => true
  accepts_nested_attributes_for :addresses, :allow_destroy => true
  accepts_nested_attributes_for :phones, :allow_destroy => true
  has_one :user

  attr_accessor :contact_list_id

  def display_name
    last_name + ', ' + first_name if first_name && last_name
  end

  def full_name
    first_name + " " + last_name  if first_name && last_name
  end
end

app/models/contact_list.rb
class ContactList < ActiveRecord::Base
  has_and_belongs_to_many :address_cards
  has_many :contact_list_associations
  has_many :users, through: :contact_list_associations, source: :contact_listable, source_type: User
  has_many :sites, through: :contact_list_associations, source: :contact_listable, source_type: Site
end

app/models/contact_list_association.rb
class ContactListAssociation < ActiveRecord::Base
  belongs_to :contact_list
  belongs_to :contact_listable, polymorphic: true
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :address_card
  validates :value, :kind, presence: true
  validates :value, :format => { :with =>  /\A([\w\!\#\z\%\&amp;\'\*\+\-\/\=\?\^\`{\|\}\~]+\.)*[\w\!\#$\%\&amp;\'\*\+\-\/\=\?\^\`{\|\}\~]+@((((([a-z0-9]{1}[a-z0-9\-]{0,62}[a-z0-9]{1})|[a-z])\.)+[a-z]{2,6})|(\d{1,3}\.){3}\d{1,3}(\:\d{1,5})?)\z/i }
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :address_card
  validates :value, :kind, presence: true
end

app/controllers/address_cards_controller.rb
=begin
Currently the way address cards have been setup is that every user will
have at least one contact list when their account is created within Backstage.
All Address Cards will be created / edited through this contact list.
=end
class AddressCardsController < ApplicationController
  before_action :require_user
  respond_to :html, :json
  expose(:user)
  expose(:address_card, attributes: :address_card_params) #{ user.address_card }
  expose(:contact_list) { user.contact_lists.first }

  def new
  end

  def show
    check_user
  end

  def edit
    check_user
  end

  def update
    if address_card.save
      redirect_to user_address_card_path(user, address_card),
        notice: 'Address Card was successfully updated.'
    else
      render :edit
    end
  end

  def create
    present_contact_list = user.contact_lists.find(
      address_card_params[:contact_list_id])
    if contact_list && contact_list.address_cards << address_card
      if present_contact_list.id != contact_list.id
        present_contact_list.address_cards << address_card
      end
      redirect_to user_contact_list_path(user, present_contact_list),
        notice: 'Address Card was successfully created.'
    else
      render action: 'new'
    end
  end

  def destroy
    address_card.destroy
    redirect_to address_cards_url,
      notice: 'Address Card was successfully destroyed.'
  end

  private

  def check_user
    if address_card.contact_lists.any? {|cl| cl.users.include?(current_user)}
      respond_with(address_card)
    else
      flash[:notice] = 'You need to login to view this Address Card'
      redirect_to login_path
    end
  end

  def address_card_params
    params.require(:address_card).permit(
      :address_card, :first_name, :last_name, :contact_list_id,
      emails_attributes: [:kind, :value, :_destroy, :id],
      addresses_attributes: [:line_1, :line_2, :line_3, :city, :province,
        :country, :postal_code, :_destroy, :id],
      phones_attributes: [:kind, :value, :_destroy, :id]
    )
  end
end

app/controllers/addresses_controller.rb
=begin
Currently the way address cards have been setup is that every user will
have at least one contact list when their account is created within Backstage.
All Address Cards will be created / edited through this contact list.
=end
class AddressesController < ApplicationController
  before_action :require_user
  respond_to :json, :html
  expose(:address)

  def show
  end
  def edit
  end
  def update
    if address.update_attributes(address_card_params)
      redirect_to user_address_card_path(current_user, current_user.address_card)
    else
      flash[:error] = "something went wrong"
      render :edit
    end
  end

  private

  def address_card_params
    params.require(:address).permit!
  end
end

app/controllers/contact_lists_controller.rb
class ContactListsController < ApplicationController
  before_action :require_user
  expose(:contact_lists, attributes: :contact_list_params, ancestor: :user)
  expose(:contact_list, attributes: :contact_list_params)
  expose(:user)
  expose(:user_contact_list) { user.contact_lists.build(contact_list_params) }
  def new
  end

  def edit
  end

  def show
  end

  def index
  end

  def update
    if contact_list.update(contact_list_params)
      redirect_to user_contact_list_path(user, contact_list), notice: 'Contact List was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def create
    if user.contact_lists << user_contact_list
      redirect_to user_contact_list_path(user, user_contact_list), notice: 'Contact List was successfully created.'
    else
      render action: 'new'
    end
  end

  def destroy
    contact_list.destroy
    redirect_to user_contact_lists_url(user), notice: 'Contact List was successfully destroyed.'
  end

  private
  def contact_list_params
    params.require(:contact_list).permit(:name, :address_card_ids => [])
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :require_user

  respond_to :json, :html
  expose(:email)

  def show
  end

  def edit
  end

  def update
    if email.update_attributes(address_card_params)
      redirect_to user_address_card_path(current_user, current_user.address_card)
    else
      flash[:error] = "something went wrong"
      render :edit
    end
  end

  private

  def address_card_params
    params.require(:email).permit!
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :require_user
  respond_to :json, :html
  expose(:phone)

  def show
  end
  def edit
  end
  def update
    if phone.update_attributes(address_card_params)
      redirect_to user_address_card_path(current_user, current_user.address_card)
    else
      flash[:error] = "something went wrong"
      render :edit
    end
  end

  private

  def address_card_params
    params.require(:phone).permit!
  end
end

app/helpers/address_book/application_helper.rb
module AddressBook
  module ApplicationHelper
  end
end

app/views/address_cards/_form.html.haml
= simple_nested_form_for([user, address_card]) do |f|
  = f.error_notification

  .inputs
    = f.input :first_name
    = f.input :last_name
    = f.fields_for :emails do |e|
      = e.input :kind, label: 'Label', placeholder: 'Work'
      = e.input :value, label: 'Email Address', placeholder: 'example@domain.com'
      = e.link_to_remove "Remove this email address"
    %p
      = f.link_to_add "Add an email address", :emails
    = f.fields_for :phones do |p|
      = p.input :kind, label: 'Label', placeholder: 'Work'
      = p.input :value, label: 'Phone Number', placeholder: '8474551588'
      = p.link_to_remove "Remove this phone number"
    %p
      = f.link_to_add "Add a phone number", :phones
    = f.fields_for :addresses do |a|
      = render 'addresses/address_fields', a: a
      = a.link_to_remove "Remove this address"
    %p
      = f.link_to_add "Add an address", :addresses
    =f.hidden_field :contact_list_id, value: (params[:contact_list] || user.contact_lists.first.id)



  .actions
    = link_to 'Cancel', :back
    = f.button :submit

app/views/address_cards/edit.html.haml
.page_content
  %h2 Edit Address Card
  =render 'form'

app/views/address_cards/index.html.haml
%h1
  Address Cards
%ul
  - address_cards.each do |ac|
    %li= link_to ac.last_name + ', ' + ac.first_name, user_address_card_path(user, ac)

= link_to 'New Address Card', new_user_address_card_path(user)

app/views/address_cards/new.html.haml
%h1 New Address Card
= render 'form'

app/views/address_cards/show.html.haml
.account_content
  = render partial: 'layouts/shared/account_navigation'
  .address_info
    %h3 Account Address
    %h4= address_card.full_name
    %ul
      - address_card.addresses.each do |a|
        %li= a.line_1
        %li= a.line_2
        %li= a.line_3
        %li= a.formated_city_state_line
        %li= a.country
        %li=link_to 'Edit Address', edit_address_path(a)
    %ul
      - address_card.emails.each do |ea|
        %li
          %span.label= "#{ea.kind} email: "
          %span= ea.value
        %li=link_to 'Edit Email', edit_email_path(ea)
    %ul
      - address_card.phones.each do |ea|
        %li
          %span.label= "#{ea.kind} phone: "
          %span= ea.value
        %li=link_to 'Edit Phone', edit_phone_path(ea)
    = link_to 'Edit Address Card', edit_user_address_card_path(current_user, address_card), class: "button"
    = link_to 'Change Password', edit_change_password_path, class: 'button'
  .user_info
    = link_to 'Edit Account', edit_user_path(current_user), class: 'edit-account'
    - if current_user.notes
      %h3 User Information
      %dl
        - current_user.notes.each do |k, v|
          %dt= k.humanize
          %dd= v

app/views/addresses/_address_fields.haml
= a.input :line_1
= a.input :line_2
= a.input :line_3
= a.input :city
= a.input :province do
  = a.subregion_select(:province, "US", {priority: ['IL'], prompt: 'Please select a state', selected: a.object.province}, required: 'region required')
= a.input :postal_code
= a.input :country do
  = a.country_select :country, {priority: %w(US), prompt: 'Please select a country', selected: a.object.country }

app/views/addresses/edit.haml
= simple_form_for address do |a|
  = render 'address_fields', a: a
  = link_to "Cancel", user_address_card_path(current_user, current_user.address_card), class: "button"
  = a.submit 'Save', class: "button"

app/views/contact_lists/_form.html.haml
= simple_form_for([user, contact_list]) do |f|
  = f.error_notification

  .inputs
    = f.input :name

  .inputs
    = f.association :address_cards, collection: user.contacts, label_method: :display_name

  .actions
    = f.button :submit

app/views/contact_lists/edit.html.haml
%h1 Edit Contact List
=render 'form'

app/views/contact_lists/index.html.haml
%h1
  Contact Lists
%ul
  - contact_lists.each do |cl|
    %li= link_to cl.name, user_contact_list_path(user, cl)


= link_to 'Back to My Account', user_address_card_path(current_user, current_user.address_card),
  class: 'button'
= link_to 'New Contact List', new_user_contact_list_path, class: 'button'

app/views/contact_lists/new.html.haml
%h1 New Contact List
=render 'form'

app/views/contact_lists/show.html.haml
%h1= contact_list.name

%ul
  - contact_list.address_cards.each do |ac|
    %li= link_to ac.last_name + ', ' + ac.first_name, user_address_card_path(user, ac)

= link_to 'Back', user_contact_lists_path,
  class: 'button'

= link_to 'Add Address', new_user_address_card_path(current_user, {contact_list: contact_list.id}),
  class: 'button'
= link_to 'Edit Contact List', edit_user_contact_list_path,
  class: 'button' unless contact_list.name == 'Contact List'

app/views/phones/edit.haml
= simple_form_for phone do |p|
  = p.input :kind
  = p.input :value

  = link_to "Cancel", user_address_card_path(current_user, current_user.address_card), class: "button"
  = p.submit 'Save', class: "button"